- name: Deploy website
  hosts: all
  become: yes

  vars:
    base_path: "/srv/nginx/pages"

  tasks:
    - name: Crear directorio destino
      file:
        path: "{{ base_path }}/{{ target_env }}"
        state: directory
        owner: nginx
        group: nginx
        mode: 0755

